version: "3"

services:
  backend:
    container_name: sae_backend
    build: ./backend
    command: yarn start:prod
    ports:
      - "4000:3005"
    env_file:
      - .backend.env
    depends_on:
      - postgres
    networks:
      - postgres
    volumes: 
      - backend:/home/node
  frontend:
    container_name: sae_frontend
    build:
      context: ./frontend
      args:
        REACT_APP_SERVER_URL: http://localhost:4000
    ports:
      - '8083:3000'
    networks:
      - postgres
    environment:
      - CI=true
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .database.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5439:5432"
    networks:
      - postgres
    restart: on-failure

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  backend: